language: node_js
node_js:
  - '0.10'
  
notifications:
  irc:
    channels:
#    - chat.freenode.net#hawkular
    on_success: change
    
before_install:
  - 'npm install -g bower gulp typescript'

script: 
  - 'gulp'

# use this line in case of building only a sub-set of plugins
#  - 'for plugin in alerts inventory metrics; do ./.travis.build.plugin.sh $plugin; done;'
