sudo: false
language: node_js
node_js:
  - '5'

npm:
  - '3'

env:
  global:
  - GH_REF: github.com/hawkular/hawkular-ui-components
  - GH_BRANCH: gh-pages


notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/3e375d2611253a8d24e3
    on_success: change
    on_failure: always
    on_start: never

cache:
  directories:
    - node_modules

before_install:
  - 'npm install -g typings bower webpack'

script: ./build.sh
