language: node_js
node_js:
  - '0.10'
  
notifications:
  irc:
    channels:
#    - chat.freenode.net#hawkular
    on_success: change
    
before_install:
  - 'npm install -g bower gulp typescript'

script:
  - 'npm install'
  - 'bower install'
  - 'gulp'